# Generated by Django 3.2.7 on 2021-09-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('COM', 'Complete'), ('INP', 'In progress'), ('TOD', 'Todo')], max_length=3)),
            ],
        ),
    ]
